### ISSUE TITLE
[Feature Request] Automatic RaidMeter Show/Hide

### ISSUE THREAD

**Issue by Darkosto** [Buuz135/RaidMeter#12]
### Hello Buuz!

While browsing my local internet haberdashery, I have come across what I would consider a **severe** issue that entails world corruption, both client and server crashes, my cat's gravity has flipped, and my entire neighborhood's computers have all blue-screened. 

But! I have a solution for all of this: What if RaidMeter had a way to hide when not being interacted with? Here's what I propose:

A timeout argument for raidmeter, that when positive makes the raidmeter automatically show when incremented and hide after said timeout has elapsed.

I think this will finally give you the Nobel for best Minecraft Mod, a reward I know that you have been seeking for some time now. Please, I don't need the credit. Take it all for yourself and live off the spoils of the **awe-inspiring** mods that you have created over the last _____ years. Thank you for your time and I hope to hear back from you in the future!

Darkosoto

P.S. Just incase your day may not be going awesome, have this joke I crafted just for you to raise your spirits: Want to hear my pizza joke? Never mind, it's too cheesy.

MC: 1.18.2
Forge: 40.1.84
Rainmeter: 2.0.2

**Comment by Buuz135** [comment]
Nah, you cant event write your name right
