### ISSUE TITLE
1.18.1 Version crashes on server start

### ISSUE THREAD

**Issue by darkphan** [Buuz135/RaidMeter#5]
Crashlog: https://gist.github.com/darkphan/38665855576a6ec4e361aabfb34c3c68

**Comment by Patrigan** [comment]
I'll take a look at it, my bad!

**Comment by Patrigan** [comment]
Bug observed, fix incoming.

**Comment by Patrigan** [comment]
PR #6 created to fix this issue. as soon as buuz merges it, a fix can be deployed. I'll see if issue #2  is still an actual issue.
