### ISSUE TITLE
[Request] Allow Commands to be Run from Function files or datapacks

### ISSUE THREAD

**Issue by Darkosto** [Buuz135/RaidMeter#8]
Hey again!

Currently, raidmeter does not support datapacks running the commands. For example, I'd like to setup a function to create and setup a raidmeter bar automatically. Even using `execute as @p` does not work and errors the `.mcfunction` file. Is there any chance you'd be able to add this functionality?

Thanks!
Darksoto

MC: 1.18.2
Forge: 40.1.25
Raidmeter: 2.0.1

**Comment by Buuz135** [comment]
I think its fixed in https://github.com/Buuz135/RaidMeter/commit/b2406a8c82465c847b0d6aef7318cfc33b2f3341
